version: '3.8'

services:
  syferlynx-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: syferlynx-applications
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    
  # Development service (optional)
  syferlynx-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    container_name: syferlynx-applications-dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    profiles:
      - dev 